export const TIME = {
  ONE_SECOND_MS: 1000,
  ONE_MINUTE_MS: 60 * 1000,
  FIFTEEN_MINUTES_MS: 15 * 60 * 1000,
  ONE_HOUR_MS: 60 * 60 * 1000,
  ONE_DAY_MS: 24 * 60 * 60 * 1000,
  ONE_WEEK_MS: 7 * 24 * 60 * 60 * 1000,

  ONE_MINUTE_SEC: 60,
  ONE_HOUR_SEC: 60 * 60,
  ONE_DAY_SEC: 24 * 60 * 60,
  ONE_YEAR_SEC: 365 * 24 * 60 * 60,
} as const

export const JWT_EXPIRY = {
  ACCESS_TOKEN: '15m',
  REFRESH_TOKEN: '7d',
} as const

export const RATE_LIMIT = {
  AUTH_LOGIN_WINDOW_MS: TIME.ONE_MINUTE_MS,
  AUTH_LOGIN_MAX: 5,

  AUTH_REGISTER_WINDOW_MS: TIME.ONE_HOUR_MS,
  AUTH_REGISTER_MAX: 3,

  AUTH_PASSWORD_WINDOW_MS: TIME.FIFTEEN_MINUTES_MS,
  AUTH_PASSWORD_MAX: 3,

  AUTH_REFRESH_WINDOW_MS: TIME.FIFTEEN_MINUTES_MS,
  AUTH_REFRESH_MAX: 20,

  INVITATION_CREATE_WINDOW_MS: TIME.ONE_HOUR_MS,
  INVITATION_CREATE_MAX: 20,

  INVITATION_ACCEPT_WINDOW_MS: TIME.FIFTEEN_MINUTES_MS,
  INVITATION_ACCEPT_MAX: 10,

  API_KEY_CREATE_WINDOW_MS: TIME.ONE_HOUR_MS,
  API_KEY_CREATE_MAX: 10,

  READ_WINDOW_MS: TIME.FIFTEEN_MINUTES_MS,
  READ_MAX: 300,

  WRITE_WINDOW_MS: TIME.FIFTEEN_MINUTES_MS,
  WRITE_MAX: 100,

  API_WINDOW_MS: TIME.FIFTEEN_MINUTES_MS,
  API_MAX_REQUESTS: 1000,
} as const
