/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health check
     * @description Check API and database connectivity status
     */
    get: operations['healthCheck']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Register new user
     * @description Create a new user account and personal organization
     */
    post: operations['register']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Login user
     * @description Authenticate user and return access token
     */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Refresh access token
     * @description Use the httpOnly refresh token cookie to obtain a new access token.
     *
     *     The refresh token is automatically sent via cookie - no request body required.
     *
     *     This endpoint rotates the refresh token (issues a new one and invalidates the old one).
     *
     *     Call this endpoint before your access token expires (15 minute lifetime).
     */
    post: operations['refreshToken']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Logout user
     * @description Invalidate the current refresh token and clear the httpOnly cookie.
     *
     *     The access token remains valid until it expires (15 minutes from issue).
     *
     *     After logout, the refresh token can no longer be used to obtain new access tokens.
     */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get current user
     * @description Get currently authenticated user with their memberships
     */
    get: operations['getCurrentUser']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Change password
     * @description Change the user's password. This operation:
     *     - Validates the current password
     *     - Enforces strong password policy (8+ chars, uppercase, lowercase, number, special char)
     *     - Increments tokenVersion to invalidate ALL existing sessions across all devices
     *     - Clears the refresh token cookie
     *
     *     **Security Note:** All active sessions will be terminated. User must log in again with the new password.
     */
    patch: operations['changePassword']
    trace?: never
  }
  '/api/v1/orgs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create organization
     * @description Create a new organization and automatically assign caller as OWNER
     */
    post: operations['createOrganization']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orgs/{slug}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get organization details
     * @description Get organization details (requires membership)
     */
    get: operations['getOrganization']
    put?: never
    post?: never
    /**
     * Delete organization
     * @description Delete organization and all associated data (requires OWNER role).
     *
     *     WARNING: This is a destructive operation that will cascade delete:
     *     - All memberships
     *     - All invitations (pending and accepted)
     *     - All API keys
     *     - All organization data
     *
     *     This action cannot be undone.
     */
    delete: operations['deleteOrganization']
    options?: never
    head?: never
    /**
     * Update organization
     * @description Update organization name and/or slug (requires ADMIN role)
     */
    patch: operations['updateOrganization']
    trace?: never
  }
  '/api/v1/orgs/{slug}/members': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List organization members
     * @description List all members of an organization with pagination (requires MEMBER role)
     */
    get: operations['listMembers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orgs/{slug}/members/{memberId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Remove member
     * @description Remove a member from the organization (ADMIN can remove members, members can remove themselves)
     */
    delete: operations['removeMember']
    options?: never
    head?: never
    /**
     * Update member role
     * @description Update a member's role (requires ADMIN role, cannot demote OWNER)
     */
    patch: operations['updateMemberRole']
    trace?: never
  }
  '/api/v1/orgs/{slug}/transfer-ownership': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Transfer ownership
     * @description Transfer OWNER role to another member (requires OWNER role)
     */
    post: operations['transferOwnership']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orgs/{slug}/invitations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List invitations
     * @description List all invitations for the organization (requires ADMIN role)
     */
    get: operations['listInvitations']
    put?: never
    /**
     * Create invitation
     * @description Create an invitation to join the organization (requires ADMIN role)
     */
    post: operations['createInvitation']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orgs/{slug}/invitations/{invitationId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Revoke invitation
     * @description Revoke a pending invitation (requires ADMIN role)
     */
    delete: operations['revokeInvitation']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/invitations/validate/{token}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Validate invitation token
     * @description Validate an invitation token and return invitation details (public endpoint).
     *
     *     Use this endpoint to check if an invitation is valid before prompting the user to accept it.
     *
     *     **Security Note:** This endpoint is public and returns organization information.
     *     It is rate-limited to prevent enumeration attacks. Repeated validation attempts
     *     may require additional verification.
     *
     *     No authentication required - the token itself serves as proof of access.
     */
    get: operations['validateInvitation']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/invitations/accept': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Accept invitation
     * @description Accept an invitation and join the organization (requires authentication)
     */
    post: operations['acceptInvitation']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orgs/{slug}/api-keys': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List API keys
     * @description List all API keys for the organization (requires ADMIN role)
     */
    get: operations['listApiKeys']
    put?: never
    /**
     * Generate API key
     * @description Generate a new API key for the organization (requires ADMIN role)
     */
    post: operations['createApiKey']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orgs/{slug}/api-keys/{keyId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Revoke API key
     * @description Revoke an API key (soft delete, requires ADMIN role)
     */
    delete: operations['revokeApiKey']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Error: {
      error: {
        /** @description Machine-readable error code */
        code: string
        /** @description Human-readable error message */
        message: string
        /** @description Additional error context */
        details?: {
          [key: string]: unknown
        }
      }
    }
    User: {
      /** @description User ID */
      id: string
      /**
       * Format: email
       * @description User email address
       */
      email: string
      /** @description User full name */
      name: string
      /**
       * Format: date-time
       * @description Account creation timestamp
       */
      createdAt: string
    }
    Organization: {
      /** @description Organization ID */
      id: string
      /** @description Organization display name */
      name: string
      /** @description URL-safe unique identifier */
      slug: string
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      createdAt: string
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updatedAt: string
    }
    Membership: {
      /** @description Membership ID */
      id: string
      /**
       * @description Member role
       * @enum {string}
       */
      role: 'OWNER' | 'ADMIN' | 'MEMBER'
      /** @description User ID */
      userId: string
      user: components['schemas']['User']
      /**
       * Format: date-time
       * @description Membership creation timestamp
       */
      createdAt: string
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updatedAt: string
    }
    Invitation: {
      /** @description Invitation ID */
      id: string
      /**
       * Format: email
       * @description Invitee email address
       */
      email: string
      /**
       * @description Role to be assigned
       * @enum {string}
       */
      role: 'OWNER' | 'ADMIN' | 'MEMBER'
      /**
       * @description Invitation status
       * @enum {string}
       */
      status: 'PENDING' | 'ACCEPTED' | 'REVOKED' | 'EXPIRED'
      /**
       * Format: date-time
       * @description Expiration timestamp
       */
      expiresAt: string
      /** @description Acceptance timestamp */
      acceptedAt?: string | null
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      createdAt: string
    }
    ApiKey: {
      /** @description API key ID */
      id: string
      /** @description Human-readable key name */
      name: string
      /** @description Array of granted scopes */
      scopes: string[]
      /** @description Last usage timestamp */
      lastUsedAt?: string | null
      /** @description Revocation timestamp */
      revokedAt?: string | null
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      createdAt: string
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updatedAt: string
    }
    PaginatedResponse: {
      data: unknown[]
      /** @description Cursor for next page (null if no more pages) */
      nextCursor: string | null
    }
  }
  responses: {
    /** @description Rate limit exceeded */
    RateLimitExceeded: {
      headers: {
        /** @description Maximum number of requests allowed in the window */
        'RateLimit-Limit'?: number
        /** @description Number of requests remaining in the current window */
        'RateLimit-Remaining'?: number
        /** @description Unix timestamp when the rate limit window resets */
        'RateLimit-Reset'?: number
        /** @description Seconds to wait before retrying */
        'Retry-After'?: number
        [name: string]: unknown
      }
      content: {
        'application/json': {
          error: {
            /** @enum {string} */
            code: 'RATE_LIMIT_EXCEEDED'
            /** @description Human-readable rate limit message */
            message: string
            details?: Record<string, never>
          }
        }
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  healthCheck: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Service is healthy */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'ok'
            /** Format: date-time */
            timestamp: string
            /** @enum {string} */
            database: 'connected'
          }
        }
      }
      /** @description Service is unhealthy */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'error'
            /** Format: date-time */
            timestamp: string
            /** @enum {string} */
            database: 'disconnected'
          }
        }
      }
    }
  }
  register: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /**
           * Format: email
           * @description User email address
           */
          email: string
          /**
           * Format: password
           * @description User password (min 8 characters)
           */
          password: string
          /** @description User full name */
          name: string
        }
      }
    }
    responses: {
      /** @description User created successfully */
      201: {
        headers: {
          'Set-Cookie'?: string
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description JWT access token */
            accessToken: string
            user: components['schemas']['User']
          }
        }
      }
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /**
           * Format: email
           * @description User email address
           */
          email: string
          /**
           * Format: password
           * @description User password
           */
          password: string
        }
      }
    }
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          'Set-Cookie'?: string
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description JWT access token */
            accessToken: string
            user: components['schemas']['User']
          }
        }
      }
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  refreshToken: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Token refreshed successfully */
      200: {
        headers: {
          'Set-Cookie'?: string
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description New JWT access token */
            accessToken: string
          }
        }
      }
      /** @description Invalid or expired refresh token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Logout successful */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getCurrentUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current user details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description User ID */
            id: string
            /**
             * Format: email
             * @description User email
             */
            email: string
            /** @description User name */
            name: string
            /**
             * Format: date-time
             * @description Account creation timestamp
             */
            createdAt: string
            memberships: {
              id: string
              /** @enum {string} */
              role: 'OWNER' | 'ADMIN' | 'MEMBER'
              organization: {
                id: string
                name: string
                slug: string
              }
              /** Format: date-time */
              createdAt: string
            }[]
          }
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  changePassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** @description User's current password for verification */
          currentPassword: string
          /** @description New password (must contain uppercase, lowercase, number, special character) */
          newPassword: string
        }
      }
    }
    responses: {
      /** @description Password changed successfully, all sessions invalidated */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation error (weak password) */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Current password is incorrect or not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  createOrganization: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** @description Organization display name */
          name: string
          /** @description URL-safe unique identifier */
          slug: string
        }
      }
    }
    responses: {
      /** @description Organization created successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            id: string
            name: string
            slug: string
            /** Format: date-time */
            createdAt: string
            /** Format: date-time */
            updatedAt: string
            membership: {
              id: string
              /** @enum {string} */
              role: 'OWNER'
              /** Format: date-time */
              createdAt: string
            }
          }
        }
      }
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Slug already exists */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  getOrganization: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Organization slug */
        slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Organization details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Organization']
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  deleteOrganization: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Organization slug */
        slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Organization deleted successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires OWNER) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  updateOrganization: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Organization slug */
        slug: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** @description Organization display name */
          name?: string
          /** @description URL-safe unique identifier */
          slug?: string
        }
      }
    }
    responses: {
      /** @description Organization updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Organization']
        }
      }
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires ADMIN) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Slug already exists */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  listMembers: {
    parameters: {
      query?: {
        /** @description Pagination cursor */
        cursor?: string
        /** @description Number of items per page */
        limit?: number
      }
      header?: never
      path: {
        /** @description Organization slug */
        slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of members */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['Membership'][]
            nextCursor: string | null
          }
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  removeMember: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Organization slug */
        slug: string
        /** @description Membership ID */
        memberId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Member removed successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization or member not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Cannot remove last OWNER */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  updateMemberRole: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Organization slug */
        slug: string
        /** @description Membership ID */
        memberId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /**
           * @description New role
           * @enum {string}
           */
          role: 'OWNER' | 'ADMIN' | 'MEMBER'
        }
      }
    }
    responses: {
      /** @description Member role updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Membership']
        }
      }
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions or invalid operation */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization or member not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Cannot remove last OWNER */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  transferOwnership: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Organization slug */
        slug: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** @description User ID of new owner */
          newOwnerId: string
        }
      }
    }
    responses: {
      /** @description Ownership transferred successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            organization: components['schemas']['Organization']
            newOwner: components['schemas']['Membership']
            formerOwner: components['schemas']['Membership']
          }
        }
      }
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires OWNER) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization or new owner not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  listInvitations: {
    parameters: {
      query?: {
        /** @description Pagination cursor */
        cursor?: string
        /** @description Number of items per page */
        limit?: number
        /** @description Filter by invitation status */
        status?: 'PENDING' | 'ACCEPTED' | 'REVOKED' | 'EXPIRED'
      }
      header?: never
      path: {
        /** @description Organization slug */
        slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of invitations */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['Invitation'][]
            nextCursor: string | null
          }
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires ADMIN) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  createInvitation: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Organization slug */
        slug: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /**
           * Format: email
           * @description Invitee email address
           */
          email: string
          /**
           * @description Role to assign
           * @default MEMBER
           * @enum {string}
           */
          role?: 'OWNER' | 'ADMIN' | 'MEMBER'
        }
      }
    }
    responses: {
      /** @description Invitation created successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            invitation: components['schemas']['Invitation']
            /** @description Invitation token (only returned once) */
            token: string
          }
        }
      }
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires ADMIN) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description User already a member or pending invitation exists */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  revokeInvitation: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Organization slug */
        slug: string
        /** @description Invitation ID */
        invitationId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Invitation revoked successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires ADMIN) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization or invitation not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Invitation already accepted or revoked */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  validateInvitation: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Invitation token */
        token: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Invitation is valid */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** Format: email */
            email: string
            /** @enum {string} */
            role: 'OWNER' | 'ADMIN' | 'MEMBER'
            organization: {
              name: string
              slug: string
            }
            /** Format: date-time */
            expiresAt: string
          }
        }
      }
      /** @description Invalid token */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Invitation expired, revoked, or already accepted */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  acceptInvitation: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** @description Invitation token */
          token: string
        }
      }
    }
    responses: {
      /** @description Invitation accepted successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            membership: components['schemas']['Membership']
            organization: components['schemas']['Organization']
          }
        }
      }
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Invalid token */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description User already a member */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Invitation expired, revoked, or already accepted */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  listApiKeys: {
    parameters: {
      query?: {
        /** @description Pagination cursor */
        cursor?: string
        /** @description Number of items per page */
        limit?: number
        /** @description Filter by active keys only (non-revoked) */
        active?: boolean
      }
      header?: never
      path: {
        /** @description Organization slug */
        slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of API keys */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['ApiKey'][]
            nextCursor: string | null
          }
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires ADMIN) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  createApiKey: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Organization slug */
        slug: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** @description Human-readable key name */
          name: string
          /**
           * @description Array of granted scopes
           * @default [
           *       "org:read"
           *     ]
           */
          scopes?: (
            | 'org:read'
            | 'org:write'
            | 'org:delete'
            | 'members:read'
            | 'members:write'
            | 'invitations:read'
            | 'invitations:write'
            | 'api-keys:read'
            | 'api-keys:write'
          )[]
        }
      }
    }
    responses: {
      /** @description API key created successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            id: string
            name: string
            /** @description The API key (only shown once, never stored in plaintext) */
            key: string
            scopes: string[]
            /** Format: date-time */
            createdAt: string
          }
        }
      }
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires ADMIN) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
  revokeApiKey: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Organization slug */
        slug: string
        /** @description API key ID */
        keyId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description API key revoked successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires ADMIN) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization or API key not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['RateLimitExceeded']
    }
  }
}
