/* eslint-disable */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    /**
     * Health check
     * @description Check API and database connectivity status
     */
    get: operations['healthCheck']
  }
  '/api/v1/auth/register': {
    /**
     * Register new user
     * @description Create a new user account and personal organization
     */
    post: operations['register']
  }
  '/api/v1/auth/login': {
    /**
     * Login user
     * @description Authenticate user and return access token
     */
    post: operations['login']
  }
  '/api/v1/auth/refresh': {
    /**
     * Refresh access token
     * @description Use refresh token cookie to get a new access token
     */
    post: operations['refreshToken']
  }
  '/api/v1/auth/logout': {
    /**
     * Logout user
     * @description Invalidate refresh token and clear cookie
     */
    post: operations['logout']
  }
  '/api/v1/auth/me': {
    /**
     * Get current user
     * @description Get currently authenticated user with their memberships
     */
    get: operations['getCurrentUser']
  }
  '/api/v1/orgs': {
    /**
     * Create organization
     * @description Create a new organization and automatically assign caller as OWNER
     */
    post: operations['createOrganization']
  }
  '/api/v1/orgs/{slug}': {
    /**
     * Get organization details
     * @description Get organization details (requires membership)
     */
    get: operations['getOrganization']
    /**
     * Delete organization
     * @description Delete organization and all associated data (requires OWNER role)
     */
    delete: operations['deleteOrganization']
    /**
     * Update organization
     * @description Update organization name and/or slug (requires ADMIN role)
     */
    patch: operations['updateOrganization']
  }
  '/api/v1/orgs/{slug}/members': {
    /**
     * List organization members
     * @description List all members of an organization with pagination (requires MEMBER role)
     */
    get: operations['listMembers']
  }
  '/api/v1/orgs/{slug}/members/{memberId}': {
    /**
     * Remove member
     * @description Remove a member from the organization (ADMIN can remove members, members can remove themselves)
     */
    delete: operations['removeMember']
    /**
     * Update member role
     * @description Update a member's role (requires ADMIN role, cannot demote OWNER)
     */
    patch: operations['updateMemberRole']
  }
  '/api/v1/orgs/{slug}/transfer-ownership': {
    /**
     * Transfer ownership
     * @description Transfer OWNER role to another member (requires OWNER role)
     */
    post: operations['transferOwnership']
  }
  '/api/v1/orgs/{slug}/invitations': {
    /**
     * List invitations
     * @description List all invitations for the organization (requires ADMIN role)
     */
    get: operations['listInvitations']
    /**
     * Create invitation
     * @description Create an invitation to join the organization (requires ADMIN role)
     */
    post: operations['createInvitation']
  }
  '/api/v1/orgs/{slug}/invitations/{invitationId}': {
    /**
     * Revoke invitation
     * @description Revoke a pending invitation (requires ADMIN role)
     */
    delete: operations['revokeInvitation']
  }
  '/api/v1/invitations/validate/{token}': {
    /**
     * Validate invitation token
     * @description Validate an invitation token and return invitation details (public endpoint)
     */
    get: operations['validateInvitation']
  }
  '/api/v1/invitations/accept': {
    /**
     * Accept invitation
     * @description Accept an invitation and join the organization (requires authentication)
     */
    post: operations['acceptInvitation']
  }
  '/api/v1/orgs/{slug}/api-keys': {
    /**
     * List API keys
     * @description List all API keys for the organization (requires ADMIN role)
     */
    get: operations['listApiKeys']
    /**
     * Generate API key
     * @description Generate a new API key for the organization (requires ADMIN role)
     */
    post: operations['createApiKey']
  }
  '/api/v1/orgs/{slug}/api-keys/{keyId}': {
    /**
     * Revoke API key
     * @description Revoke an API key (soft delete, requires ADMIN role)
     */
    delete: operations['revokeApiKey']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    Error: {
      error: {
        /** @description Machine-readable error code */
        code: string
        /** @description Human-readable error message */
        message: string
        /** @description Additional error context */
        details?: {
          [key: string]: unknown
        }
      }
    }
    User: {
      /** @description User ID */
      id: string
      /**
       * Format: email
       * @description User email address
       */
      email: string
      /** @description User full name */
      name: string
      /**
       * Format: date-time
       * @description Account creation timestamp
       */
      createdAt: string
    }
    Organization: {
      /** @description Organization ID */
      id: string
      /** @description Organization display name */
      name: string
      /** @description URL-safe unique identifier */
      slug: string
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      createdAt: string
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updatedAt: string
    }
    Membership: {
      /** @description Membership ID */
      id: string
      /**
       * @description Member role
       * @enum {string}
       */
      role: 'OWNER' | 'ADMIN' | 'MEMBER'
      /** @description User ID */
      userId: string
      user: components['schemas']['User']
      /**
       * Format: date-time
       * @description Membership creation timestamp
       */
      createdAt: string
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updatedAt: string
    }
    Invitation: {
      /** @description Invitation ID */
      id: string
      /**
       * Format: email
       * @description Invitee email address
       */
      email: string
      /**
       * @description Role to be assigned
       * @enum {string}
       */
      role: 'OWNER' | 'ADMIN' | 'MEMBER'
      /**
       * @description Invitation status
       * @enum {string}
       */
      status: 'PENDING' | 'ACCEPTED' | 'REVOKED' | 'EXPIRED'
      /**
       * Format: date-time
       * @description Expiration timestamp
       */
      expiresAt: string
      /** @description Acceptance timestamp */
      acceptedAt?: string | null
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      createdAt: string
    }
    ApiKey: {
      /** @description API key ID */
      id: string
      /** @description Human-readable key name */
      name: string
      /** @description Array of granted scopes */
      scopes: string[]
      /** @description Last usage timestamp */
      lastUsedAt?: string | null
      /** @description Revocation timestamp */
      revokedAt?: string | null
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      createdAt: string
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updatedAt: string
    }
    PaginatedResponse: {
      data: unknown[]
      /** @description Cursor for next page (null if no more pages) */
      nextCursor: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  /**
   * Health check
   * @description Check API and database connectivity status
   */
  healthCheck: {
    responses: {
      /** @description Service is healthy */
      200: {
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'ok'
            /** Format: date-time */
            timestamp: string
            /** @enum {string} */
            database: 'connected'
          }
        }
      }
      /** @description Service is unhealthy */
      503: {
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'error'
            /** Format: date-time */
            timestamp: string
            /** @enum {string} */
            database: 'disconnected'
          }
        }
      }
    }
  }
  /**
   * Register new user
   * @description Create a new user account and personal organization
   */
  register: {
    requestBody: {
      content: {
        'application/json': {
          /**
           * Format: email
           * @description User email address
           */
          email: string
          /**
           * Format: password
           * @description User password (min 8 characters)
           */
          password: string
          /** @description User full name */
          name: string
        }
      }
    }
    responses: {
      /** @description User created successfully */
      201: {
        headers: {
          'Set-Cookie'?: string
        }
        content: {
          'application/json': {
            /** @description JWT access token */
            accessToken: string
            user: components['schemas']['User']
          }
        }
      }
      /** @description Validation error */
      400: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Email already registered */
      409: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Login user
   * @description Authenticate user and return access token
   */
  login: {
    requestBody: {
      content: {
        'application/json': {
          /**
           * Format: email
           * @description User email address
           */
          email: string
          /**
           * Format: password
           * @description User password
           */
          password: string
        }
      }
    }
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          'Set-Cookie'?: string
        }
        content: {
          'application/json': {
            /** @description JWT access token */
            accessToken: string
            user: components['schemas']['User']
          }
        }
      }
      /** @description Invalid credentials */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Refresh access token
   * @description Use refresh token cookie to get a new access token
   */
  refreshToken: {
    responses: {
      /** @description Token refreshed successfully */
      200: {
        headers: {
          'Set-Cookie'?: string
        }
        content: {
          'application/json': {
            /** @description New JWT access token */
            accessToken: string
          }
        }
      }
      /** @description Invalid or expired refresh token */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Logout user
   * @description Invalidate refresh token and clear cookie
   */
  logout: {
    responses: {
      /** @description Logout successful */
      204: {
        content: never
      }
    }
  }
  /**
   * Get current user
   * @description Get currently authenticated user with their memberships
   */
  getCurrentUser: {
    responses: {
      /** @description Current user details */
      200: {
        content: {
          'application/json': {
            /** @description User ID */
            id: string
            /**
             * Format: email
             * @description User email
             */
            email: string
            /** @description User name */
            name: string
            /**
             * Format: date-time
             * @description Account creation timestamp
             */
            createdAt: string
            memberships: {
              id: string
              /** @enum {string} */
              role: 'OWNER' | 'ADMIN' | 'MEMBER'
              organization: {
                id: string
                name: string
                slug: string
              }
              /** Format: date-time */
              createdAt: string
            }[]
          }
        }
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Create organization
   * @description Create a new organization and automatically assign caller as OWNER
   */
  createOrganization: {
    requestBody: {
      content: {
        'application/json': {
          /** @description Organization display name */
          name: string
          /** @description URL-safe unique identifier */
          slug: string
        }
      }
    }
    responses: {
      /** @description Organization created successfully */
      201: {
        content: {
          'application/json': {
            id: string
            name: string
            slug: string
            /** Format: date-time */
            createdAt: string
            /** Format: date-time */
            updatedAt: string
            membership: {
              id: string
              /** @enum {string} */
              role: 'OWNER'
              /** Format: date-time */
              createdAt: string
            }
          }
        }
      }
      /** @description Validation error */
      400: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Slug already exists */
      409: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Get organization details
   * @description Get organization details (requires membership)
   */
  getOrganization: {
    parameters: {
      path: {
        /** @description Organization slug */
        slug: string
      }
    }
    responses: {
      /** @description Organization details */
      200: {
        content: {
          'application/json': components['schemas']['Organization']
        }
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Delete organization
   * @description Delete organization and all associated data (requires OWNER role)
   */
  deleteOrganization: {
    parameters: {
      path: {
        /** @description Organization slug */
        slug: string
      }
    }
    responses: {
      /** @description Organization deleted successfully */
      204: {
        content: never
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires OWNER) */
      403: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Update organization
   * @description Update organization name and/or slug (requires ADMIN role)
   */
  updateOrganization: {
    parameters: {
      path: {
        /** @description Organization slug */
        slug: string
      }
    }
    requestBody: {
      content: {
        'application/json': {
          /** @description Organization display name */
          name?: string
          /** @description URL-safe unique identifier */
          slug?: string
        }
      }
    }
    responses: {
      /** @description Organization updated successfully */
      200: {
        content: {
          'application/json': components['schemas']['Organization']
        }
      }
      /** @description Validation error */
      400: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires ADMIN) */
      403: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Slug already exists */
      409: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * List organization members
   * @description List all members of an organization with pagination (requires MEMBER role)
   */
  listMembers: {
    parameters: {
      query?: {
        /** @description Pagination cursor */
        cursor?: string
        /** @description Number of items per page */
        limit?: number
      }
      path: {
        /** @description Organization slug */
        slug: string
      }
    }
    responses: {
      /** @description List of members */
      200: {
        content: {
          'application/json': {
            data: components['schemas']['Membership'][]
            nextCursor: string | null
          }
        }
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Remove member
   * @description Remove a member from the organization (ADMIN can remove members, members can remove themselves)
   */
  removeMember: {
    parameters: {
      path: {
        /** @description Organization slug */
        slug: string
        /** @description Membership ID */
        memberId: string
      }
    }
    responses: {
      /** @description Member removed successfully */
      204: {
        content: never
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions */
      403: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization or member not found */
      404: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Cannot remove last OWNER */
      409: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Update member role
   * @description Update a member's role (requires ADMIN role, cannot demote OWNER)
   */
  updateMemberRole: {
    parameters: {
      path: {
        /** @description Organization slug */
        slug: string
        /** @description Membership ID */
        memberId: string
      }
    }
    requestBody: {
      content: {
        'application/json': {
          /**
           * @description New role
           * @enum {string}
           */
          role: 'OWNER' | 'ADMIN' | 'MEMBER'
        }
      }
    }
    responses: {
      /** @description Member role updated successfully */
      200: {
        content: {
          'application/json': components['schemas']['Membership']
        }
      }
      /** @description Validation error */
      400: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions or invalid operation */
      403: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization or member not found */
      404: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Cannot remove last OWNER */
      409: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Transfer ownership
   * @description Transfer OWNER role to another member (requires OWNER role)
   */
  transferOwnership: {
    parameters: {
      path: {
        /** @description Organization slug */
        slug: string
      }
    }
    requestBody: {
      content: {
        'application/json': {
          /** @description User ID of new owner */
          newOwnerId: string
        }
      }
    }
    responses: {
      /** @description Ownership transferred successfully */
      200: {
        content: {
          'application/json': {
            organization: components['schemas']['Organization']
            newOwner: components['schemas']['Membership']
            formerOwner: components['schemas']['Membership']
          }
        }
      }
      /** @description Validation error */
      400: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires OWNER) */
      403: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization or new owner not found */
      404: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * List invitations
   * @description List all invitations for the organization (requires ADMIN role)
   */
  listInvitations: {
    parameters: {
      query?: {
        /** @description Pagination cursor */
        cursor?: string
        /** @description Number of items per page */
        limit?: number
        /** @description Filter by invitation status */
        status?: 'PENDING' | 'ACCEPTED' | 'REVOKED' | 'EXPIRED'
      }
      path: {
        /** @description Organization slug */
        slug: string
      }
    }
    responses: {
      /** @description List of invitations */
      200: {
        content: {
          'application/json': {
            data: components['schemas']['Invitation'][]
            nextCursor: string | null
          }
        }
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires ADMIN) */
      403: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Create invitation
   * @description Create an invitation to join the organization (requires ADMIN role)
   */
  createInvitation: {
    parameters: {
      path: {
        /** @description Organization slug */
        slug: string
      }
    }
    requestBody: {
      content: {
        'application/json': {
          /**
           * Format: email
           * @description Invitee email address
           */
          email: string
          /**
           * @description Role to assign
           * @default MEMBER
           * @enum {string}
           */
          role?: 'OWNER' | 'ADMIN' | 'MEMBER'
        }
      }
    }
    responses: {
      /** @description Invitation created successfully */
      201: {
        content: {
          'application/json': {
            invitation: components['schemas']['Invitation']
            /** @description Invitation token (only returned once) */
            token: string
          }
        }
      }
      /** @description Validation error */
      400: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires ADMIN) */
      403: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description User already a member or pending invitation exists */
      409: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Revoke invitation
   * @description Revoke a pending invitation (requires ADMIN role)
   */
  revokeInvitation: {
    parameters: {
      path: {
        /** @description Organization slug */
        slug: string
        /** @description Invitation ID */
        invitationId: string
      }
    }
    responses: {
      /** @description Invitation revoked successfully */
      204: {
        content: never
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires ADMIN) */
      403: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization or invitation not found */
      404: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Invitation already accepted or revoked */
      410: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Validate invitation token
   * @description Validate an invitation token and return invitation details (public endpoint)
   */
  validateInvitation: {
    parameters: {
      path: {
        /** @description Invitation token */
        token: string
      }
    }
    responses: {
      /** @description Invitation is valid */
      200: {
        content: {
          'application/json': {
            /** Format: email */
            email: string
            /** @enum {string} */
            role: 'OWNER' | 'ADMIN' | 'MEMBER'
            organization: {
              name: string
              slug: string
            }
            /** Format: date-time */
            expiresAt: string
          }
        }
      }
      /** @description Invalid token */
      404: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Invitation expired, revoked, or already accepted */
      410: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Accept invitation
   * @description Accept an invitation and join the organization (requires authentication)
   */
  acceptInvitation: {
    requestBody: {
      content: {
        'application/json': {
          /** @description Invitation token */
          token: string
        }
      }
    }
    responses: {
      /** @description Invitation accepted successfully */
      201: {
        content: {
          'application/json': {
            membership: components['schemas']['Membership']
            organization: components['schemas']['Organization']
          }
        }
      }
      /** @description Validation error */
      400: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Invalid token */
      404: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description User already a member */
      409: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Invitation expired, revoked, or already accepted */
      410: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * List API keys
   * @description List all API keys for the organization (requires ADMIN role)
   */
  listApiKeys: {
    parameters: {
      query?: {
        /** @description Pagination cursor */
        cursor?: string
        /** @description Number of items per page */
        limit?: number
        /** @description Filter by active keys only (non-revoked) */
        active?: boolean
      }
      path: {
        /** @description Organization slug */
        slug: string
      }
    }
    responses: {
      /** @description List of API keys */
      200: {
        content: {
          'application/json': {
            data: components['schemas']['ApiKey'][]
            nextCursor: string | null
          }
        }
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires ADMIN) */
      403: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Generate API key
   * @description Generate a new API key for the organization (requires ADMIN role)
   */
  createApiKey: {
    parameters: {
      path: {
        /** @description Organization slug */
        slug: string
      }
    }
    requestBody: {
      content: {
        'application/json': {
          /** @description Human-readable key name */
          name: string
          /**
           * @description Array of granted scopes
           * @default [
           *   "org:read"
           * ]
           */
          scopes?: (
            | 'org:read'
            | 'org:write'
            | 'org:delete'
            | 'members:read'
            | 'members:write'
            | 'invitations:read'
            | 'invitations:write'
            | 'api-keys:read'
            | 'api-keys:write'
          )[]
        }
      }
    }
    responses: {
      /** @description API key created successfully */
      201: {
        content: {
          'application/json': {
            id: string
            name: string
            /** @description The API key (only shown once, never stored in plaintext) */
            key: string
            scopes: string[]
            /** Format: date-time */
            createdAt: string
          }
        }
      }
      /** @description Validation error */
      400: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires ADMIN) */
      403: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization not found or not a member */
      404: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  /**
   * Revoke API key
   * @description Revoke an API key (soft delete, requires ADMIN role)
   */
  revokeApiKey: {
    parameters: {
      path: {
        /** @description Organization slug */
        slug: string
        /** @description API key ID */
        keyId: string
      }
    }
    responses: {
      /** @description API key revoked successfully */
      204: {
        content: never
      }
      /** @description Not authenticated */
      401: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Insufficient permissions (requires ADMIN) */
      403: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Organization or API key not found */
      404: {
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
}
